print("salut tout le monde ")
print("moi c'est yannick")
print("je suis un développeur")
print("je suis passionné par la programmation")
print("j'aime apprendre de nouvelles choses")
print("suivez avec moi mon aventur dans le monde  de la programmaotion")
print("merci de votre attention")
print("modification")
print("modification 2")
